spring.application.name=claim-system

spring.security.user.name=admin
spring.security.user.password=admin

server.servlet.contextPath=/api/v1

spring.datasource.url=jdbc:postgresql://localhost:5432/claim-system
spring.datasource.username=postgres
spring.datasource.password=root
# Spring Boot can infer this from the URL
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true